# Namespace for deployment
namespace: my-namespace

# --------------------------
# Spring Boot Application
# --------------------------
spring:
  replicaCount: 1
  image:
    repository: phea12/spring-homework-image # Jenkins pushes here
    pullPolicy: IfNotPresent
    tag: "0.0.0" # Jenkins updates this
  service:
    type: ClusterIP
    port: 8080
  resources: {}
  livenessProbe:
    httpGet:
      path: /
      port: 8080
  readinessProbe:
    httpGet:
      path: /
      port: 8080

# --------------------------
# PostgreSQL Database
# --------------------------
postgres:
  enabled: true
  image: postgres:15
  username: springuser
  password: springpass # stored as Secret in k8s
  database: springdb
  port: 5432
  storage: 1Gi