# Namespace for deployment
namespace: my-namespace

# --------------------------
# Spring Boot Application
# --------------------------
spring:
  replicaCount: 1
  image:
    repository: phea12/spring-homework-image # Jenkins pushes here
    pullPolicy: IfNotPresent
    tag: "13" # Jenkins updates this
  service:
    type: ClusterIP
    port: 9090
  resources: {}

# --------------------------
# PostgreSQL Database
# --------------------------
postgres:
  enabled: true
  image: postgres:17
  username: springuser
  password: springpass # stored as Secret in k8s
  database: springdb
  port: 5432
  storage: 1Gi