apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.spring.replicas }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: "{{ .Values.spring.image.imageRepository }}:{{ .Values.spring.image.tag }}"
        ports:
        - containerPort: {{ .Values.spring.port }}
        envFrom:
        - configMapRef:
            name: spring-config
        - secretRef:
            name: postgres-secret
