apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.spring.replicas }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}"
        ports:
        - containerPort: {{ .Values.spring.service.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: spring-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: spring-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-pass
